name: Release
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22", cache: "npm" }
      - run: npm ci || npm i
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: t1-provenance
          path: |
            data/packs/*.json
            data/schemas/*.json
            scripts/**/*
